name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environment
        default: TEST
        options:
          - TEST
          - PROD

jobs:
  build-test-lint:
    name: Build artifacts
    uses: ./.github/workflows/build-test-lint.yml
  codeql-scan:
    name: CodeQL scan
    uses: ./.github/workflows/codeql-scan.yml
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs:
      - build-test-lint
      - codeql-scan

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: snarbanking-artifacts

      - name: Display structure of downloaded files
        run: ls -R
